config/routes.rb
Bite::Application.routes.draw do
  resources :users

  resources :visits

  resources :dishes

  resources :restaurants

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :dish_id, :note, :rating, :restaurant_id, :user_id
  belongs_to :restaurant
  belongs_to :dish
  belongs_to :user
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:user_id, User.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br />
    <%= f.collection_select(:restaurant_id, Restaurant.all, :id, :name) %>
    <%#= f.number_field :restaurant_id %>
  </div>
  <div class="field">
    <%= f.label :dish_id %><br />
    <%= f.collection_select(:dish_id, Dish.all, :id, :name) %>
    <%#= f.number_field :dish_id %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table border=1>
  <tr>
    <th>Note</th>
    <th>User</th>
    <th>Restaurant</th>
    <th>Dish</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.note %></td>
    <td><%= visit.user.name %></td>
    <td><%= visit.restaurant.name %></td>
    <td><%= visit.dish.name %></td>
    <td><%= visit.rating %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Note:</b>
  <%= @visit.note %>
</p>

<p>
  <b>User:</b>
  <%= @visit.user.name %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @visit.restaurant.name %>
</p>

<p>
  <b>Dish:</b>
  <%= @visit.dish.name %>
</p>

<p>
  <b>Rating:</b>
  <%= @visit.rating %>
</p>


<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>